services:
  app:
    build: .
    container_name: bb_app
    ports:
      - "${HTTPPORT}:80"
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - APP_ENV=dev
      - DEBUG=true
    command: ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
    user: "${UID}:${GID}"
  mailhog:
    image: mailhog/mailhog
    container_name: bb_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
